<?php
return [
    'site_title'   => 'Entropic Networks - Technology in Balance',
    'meta_desc'    => 'Entropic Networks transforms technological chaos into competitive advantage.',
    'author'       => 'Entropic Networks',
    'nav_home'     => 'Home',
    'nav_tour'     => 'Services',
    'nav_pricing'  => 'Plans',
    'nav_about'    => 'About',
    'nav_blog'     => 'Blog',
    'blog_home'    => 'Blog Home',
    'blog_single'  => 'Single Blog Post',
    'nav_contact'  => 'Contact',
    'login'        => 'Log in',
    'get_started'  => 'Get Started',
    'hero_title'   => 'Everything you need<br>to transform technological chaos into competitive advantage',
    'hero_sub'     => 'Entropic Networks offers comprehensive technological solutions that optimize system performance and protect critical information with a preventive, personalized, and professional approach.',
    'hero_cta'     => 'Our Services',
    'signup_title' => 'Try Entropic Networks Free',
    'signup_sub'   => 'Sign up to try our Basic Plan FREE for 30 days! No credit card needed.',
    'your_email'   => 'Your email',
    'email_placeholder' => 'Enter your email address',
    'signup_btn'   => 'SIGN UP',
    'why_title'    => 'Why Choose Entropic Networks',
    'why_sub'      => 'More than 300,000 satisfied customers trust our technological solutions worldwide',
    'why_cta'      => 'Explore Our Services',
    'video_title'  => 'Grow your business with technology in balance!',
    'video_sub'    => 'Discover how Entropic Networks can transform your technological challenges into effective solutions that drive your company\'s productivity.',
    'watch_video'  => 'Watch Video',
    'signup2_title'=> 'Ready to bring technology in balance with Entropic Networks?',
    'signup2_sub'  => 'Sign up to try our Basic Plan FREE for 30 days! No credit card needed.',
    'footer_title' => 'About Entropic Networks',
    'footer_desc'  => 'At Entropic Networks, we specialize in providing a comprehensive range of technological services designed to ensure optimal performance of your equipment and systems.',
    'learn_more'   => 'Learn more',
];
