<?php
return [
    'site_title'   => 'Entropic Networks - Tecnología en Equilibrio',
    'meta_desc'    => 'Entropic Networks transforma el caos tecnológico en ventaja competitiva.',
    'author'       => 'Entropic Networks',
    'nav_home'     => 'Inicio',
    'nav_tour'     => 'Servicios',
    'nav_pricing'  => 'Planes',
    'nav_about'    => 'Nosotros',
    'nav_blog'     => 'Blog',
    'blog_home'    => 'Inicio del Blog',
    'blog_single'  => 'Entrada Individual',
    'nav_contact'  => 'Contacto',
    'login'        => 'Iniciar sesión',
    'get_started'  => 'Comenzar',
    'hero_title'   => 'Todo lo que necesitas<br>para transformar el caos tecnológico en ventaja competitiva',
    'hero_sub'     => 'Entropic Networks ofrece soluciones tecnológicas integrales que optimizan el rendimiento de los sistemas y protegen la información crítica con un enfoque preventivo, personalizado y profesional.',
    'hero_cta'     => 'Nuestros Servicios',
    'signup_title' => 'Prueba Entropic Networks Gratis',
    'signup_sub'   => '¡Regístrate para probar nuestro Plan Básico GRATIS por 30 días! No se necesita tarjeta de crédito.',
    'your_email'   => 'Tu correo',
    'email_placeholder' => 'Introduce tu dirección de correo',
    'signup_btn'   => 'REGISTRARSE',
    'why_title'    => 'Por qué elegir Entropic Networks',
    'why_sub'      => 'Más de 300.000 clientes satisfechos confían en nuestras soluciones tecnológicas en todo el mundo',
    'why_cta'      => 'Explorar nuestros servicios',
    'video_title'  => '¡Haz crecer tu negocio con tecnología en equilibrio!',
    'video_sub'    => 'Descubre cómo Entropic Networks puede transformar tus desafíos tecnológicos en soluciones efectivas que impulsen la productividad de tu empresa.',
    'watch_video'  => 'Ver vídeo',
    'signup2_title'=> '¿Listo para equilibrar la tecnología con Entropic Networks?',
    'signup2_sub'  => '¡Regístrate para probar nuestro Plan Básico GRATIS por 30 días! No se necesita tarjeta de crédito.',
    'footer_title' => 'Acerca de Entropic Networks',
    'footer_desc'  => 'En Entropic Networks nos especializamos en brindar una gama integral de servicios tecnológicos diseñados para garantizar el óptimo rendimiento de tus equipos y sistemas.',
    'learn_more'   => 'Saber más',
];
